version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bimeta-v1-app
    ports:
      - "8081:80"
    volumes:
      - ./code:/var/www/html
    networks:
      - bimeta-net

networks:
  bimeta-net:
    driver: bridge
